typography_spectrum: 0.5336
color:
  brandColors:
    - '#202120'
    - '#a7956d'
    - '#e8d8c6'
    - '#b4291f'
    - '#c06354'
  brandStrength: 0.6875
  lightness: 0.7631590138189495
  saturation: 0.34384338557720184
  rhythmicContrast: 0.22948962124064565
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.93235
analytics:
  google: null
  facebook: null
  twitter: null
name: Joey Sturgis Tones
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Joey Sturgis Tones
description: Unleash Your Creativity
purpose: []
